version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci --prefer-offline --no-audit
  
  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - npm run lint
  
  build:
    commands:
      - echo "Building the React application..."
      - npm run build:prod
  
  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "Build artifacts are in the dist directory"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  name: nexus-mint-build-$(date +%Y-%m-%d)

cache:
  paths:
    - 'node_modules/**/*'
    - '.npm/**/*'