version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo Building the React app...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: build-output

cache:
  paths:
    - 'node_modules/**/*'