version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - export NODE_OPTIONS=--max_old_space_size=4096
  
  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - npm run lint
  
  build:
    commands:
      - echo "Building the React application..."
      - npm run build
  
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  name: nexus-mint-build-$(date +%Y-%m-%d)

cache:
  paths:
    - 'node_modules/**/*'