version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps
  
  pre_build:
    commands:
      - echo Running linter...
      - npm run lint
      - echo Running tests...
      - npm run test
  
  build:
    commands:
      - echo Building application...
      - npm run build:prod
  
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: nexus-mint-build

cache:
  paths:
    - 'node_modules/**/*'