// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qncfxkgjydeiefyhyllk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuY2Z4a2dqeWRlaWVmeWh5bGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTk3NTEsImV4cCI6MjA2NzM3NTc1MX0.OqbFtCDzHr08_GldcbxvoaxIqIAao_g7U8ys0WjNYBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});